### PR TITLE
Modified ELF dynamic symtab list: added additional space separator

### PR DESCRIPTION
**Pull request by santana705736**

### CODE REVIEW

**Comment by santana705736** [comment]
As I understand, the 'readelf -sW' command can return empty 'name' field.
Then, after the split operation, the length of the array will be greater than possible.
Therefore, we will get the 'index out of range' error.
To avoid this, we must include the 'space' symbol to separator's symbol list.

**Comment by santana705736** [comment]
Hello Yury,
OS: FreeBSD 13-2 STABLE

Please look the patch and files from archive:

As You can see, the sting with index 0 has no name.
The size if syms is 73351.
The size of splitted syms is 73352 (first index is 0, last index is 73351)

When we try to copy from one array to another, we will get "Out Of Range" error in last array's element.

BR, Alexey

[data.tgz](https://github.com/yugr/Implib.so/files/12021653/data.tgz)
[patch.txt](https://github.com/yugr/Implib.so/files/12021654/patch.txt)

**Comment by yugr** [comment]
Ok, that sounds reasonable. Still, to be sure, could you attach the output of readelf and c++filt for problematic file? I think this patch should do this:
```
diff --git a/implib-gen.py b/implib-gen.py
index 5b576c8..5a33e83 100755
--- a/implib-gen.py
+++ b/implib-gen.py
@@ -72,6 +72,9 @@ def collect_syms(f):
   # --dyn-syms does not always work for some reason so dump all symtabs
   out, _ = run(['readelf', '-sW', f])

+  with open('readelf.txt', 'w') as fd:
+    fd.write(out)
+
   toc = None
   syms = []
   syms_set = set()
@@ -110,6 +113,8 @@ def collect_syms(f):
   # Also collected demangled names
   if syms:
     out, _ = run(['c++filt'], '\n'.join((sym['Name'] for sym in syms)))
+    with open('cppfilt.txt', 'w') as fd:
+      fd.write(out)
     for i, name in enumerate(out.split("\n")):
       syms[i]['Demangled Name'] = name
```

**Comment by santana705736** [comment]
Hello Yury,

Please look the output of files.

BR, Alexey

[data.tgz](https://github.com/yugr/Implib.so/files/12026300/data.tgz)
[patch.txt](https://github.com/yugr/Implib.so/files/12026301/patch.txt)

**Comment by yugr** [comment]
Thank you.

So it seems the root cause is that c++filt on your system is adding a parasitic newline at the end of output, right?

I think we can fix this by
1) skipping trailing empty lines in c++filt output
1) ignoring symbols with empty names 

Could you check if this patch helps?

```
diff --git a/implib-gen.py b/implib-gen.py
index 5b576c8..ac48b75 100755
--- a/implib-gen.py
+++ b/implib-gen.py
@@ -90,6 +90,8 @@ def collect_syms(f):
     elif toc is not None:
       sym = parse_row(words, toc, ['Value'])
       name = sym['Name']
+      if not name:
+        continue
       if name in syms_set:
         continue
       syms_set.add(name)
@@ -110,6 +112,7 @@ def collect_syms(f):
   # Also collected demangled names
   if syms:
     out, _ = run(['c++filt'], '\n'.join((sym['Name'] for sym in syms)))
+    out = out.rstrip('\n')  # Some c++filts append newlines at the end
     for i, name in enumerate(out.split("\n")):
       syms[i]['Demangled Name'] = name
```

**Comment by yugr** [comment]
Done. Thank you for reporting the issue.

**Pull request closed without merging**
